### ISSUE TITLE
loader for collect cannot handle commands.collect

### ISSUE THREAD

**Issue by kbroughton** [duo-labs/cloudmapper#108]
I just pulled latest from master on my mac.
I have python3.6 installed and followed the README to create the virtualenv.

(venv)
kbroughton at Kestens-Macbook-Pro in ~/tools/cloudmapper on master [?]
$ python cloudmapper.py configure add-account --config-file test-config.json --name test --id xxxxxxxxxx
Traceback (most recent call last):
  File "cloudmapper.py", line 68, in <module>
    main()
  File "cloudmapper.py", line 52, in main
    module = importer.find_module(command_name).load_module(full_package_name)
  File "<frozen importlib._bootstrap_external>", line 398, in _check_name_wrapper
ImportError: loader for collect cannot handle commands.collect
(venv)

I then pulled a container, the official python:3.6-stretch
and followed the steps again.  Same error inside the container.

I rolled back to this commit and everything worked in both environments.

437dd11207a2122836470a7698f83641b662e433

It looks like a commit in the last month has broken imports.

**Comment by 0xdabbad00** [comment]
I believe the issue here is due to Python 3. I was testing the latest work with Python 2.7.  I need to update CloudMapper to not only support Python 3, but to stop supporting Python 2.7 as documented in https://github.com/duo-labs/cloudmapper/issues/107  I apologize for this. As an interim work-around you could use Python 2.7, but I'll try to update the codebase in the next few days to work with Python 3.

**Comment by toniblyx** [comment]
Yes, I went through the same issue and it is the Python version.

In your Mac just make sure you use Python 2.7 and it works fine.

**Comment by 0xdabbad00** [comment]
Resolved by updating the code to use Python 3 in #107
