### ISSUE TITLE
multi account support for network visualization

### ISSUE THREAD

**Issue by ebartz** [duo-labs/cloudmapper#112]
Hi there,

I currently have over 70 accounts under 1 payer account. I have configured multiple accounts in my config.json but it seems like the prepare step only builds one account at a time.

Is there any way in which this tool also visualizes multiple accounts and the connections between those?

**Comment by 0xdabbad00** [comment]
You are correct. The `prepare` command only allows one account at a time.  The `wot` command allows multiple accounts.  Mapping out network resources (via `prepare`) is currently resulting in graphs that are often too complex to display or understand, so mapping out the network resources of multiple accounts at once would make things worse.  The likely best course of action here would be for me to filter out anything below the subnet level in order to be able to see cross-account network connections.

**Comment by hhh0505** [comment]
@ebartz how do you work with multiple accounts? Can you use Assume role or do you need multiple access keys?

**Comment by 0xdabbad00** [comment]
Closing this as I need to reduce the complexity of graphs before I even attempt to add more nodes and complexity.
