### ISSUE TITLE
cloudmapper.py prepare -  0 external CIDRs built

### ISSUE THREAD

**Issue by VadimS1** [duo-labs/cloudmapper#165]
We put only one CIDR in config.json but we have fair amount of subnets.
Should we put all of them?
We are getting:
- 0 external CIDRs built
- 0 connections built

**Comment by 0xdabbad00** [comment]
When CloudMapper prints out "0 external CIDRs built", what it is saying is that the Security Groups did not reference any external CIDRs.  For example, some people will allow SSH only from their home or office IP addresses, which would show up as a CIDR.

The 0 connections built means that nothing in the network can talk to anything else, which likely means that CloudMapper did not identify any nodes in the network, which means either you ran this in an AWS account that is not using any EC2's or other network resources, or you did not run the `collect` step (or something broke when running the collect step).

You don't need to write any CIDRs in the `config.json` file.  That is just to help you better understand what those CIDRs are, so instead of just showing `1.2.3.4/32`, CloudMapper will show `Office IP`.

**Comment by 0xdabbad00** [comment]
Closing due to staleness. I believe the above answer resolved this.
