### ISSUE TITLE
Evaluate Network ACLs

### ISSUE THREAD

**Issue by j4v** [duo-labs/cloudmapper#214]
Currently the tool only evaluates Security Groups to determine the traffic allowed between networks.

Considering that ACLs could be disallowing traffic that seems allowed when only looking at SGs, it would be good to at least have some visibility on the former.

**Comment by Justin-W** [comment]
I agree. It would be useful to take network ACLs into account, and use them to add additional edges and/or remove (or render differently) any edges that would be permitted by peerings and/or security groups but which are denied due to NACL rules.

**Comment by 0xdabbad00** [comment]
I haven't seen NACLs used often enough to warrant investing the time in this, so I'm going to mark this as low priority for me.

**Comment by jshodd** [comment]
Hey @0xdabbad00, I'm currently working on a project that would definitely benefit from including ACLs like requested here. I'm somewhat familiar with the codebase (thanks for the recent merge! 😄 ) and would totally be willing to make this change in my off time. One thing that would definitely help is if you could give me a rough overview on where I'm going to need to make code changes to implement this. If you don't have time to talk me through it I can try to work it out on my own though. Thanks!

**Comment by 0xdabbad00** [comment]
This could be a tough task but I'll try to explain what I would do for it.  The function responsible for deciding which nodes can talk to each other is: https://github.com/duo-labs/cloudmapper/blob/3b8022c60f5172f8aa6ccaac1dfcb2b622d95ed8/commands/prepare.py#L212

For every network resource this function looks at the Security Groups to make connections between them.  Off the top of my head, I think what I would do would be to add code after all the connections have been made to remove the connections that would not be possible due to NACLs.  You'd basically walk each node and looks at the connections it has.  You'd compare the IPs of the inbound connections, with the NACLs associated with that subnet and remove the connections that would not be possible.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
