### ISSUE TITLE
Have ELB (a NLB), but not seeing line from "Internet" to it

### ISSUE THREAD

**Issue by jgn** [duo-labs/cloudmapper#218]
I've constrained the `--prepare` phase to a particular VPC. I have an internet-facing NLB associated with it but I'm not seeing the NLB or the "Internet" icon on the map. Seems odd. Am I doing something . . . wrong?

**Comment by 0xdabbad00** [comment]
If the NLB has a Security Group associated with it that allows `0.0.0.0/0` to talk to it, then it should show up.   I would double check that is the case (that communication isn't proxied through something else, or that traffic is not restricted to specific Internet IPs).

**Comment by jgn** [comment]
So I checked our NLBs. [This](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html#target-security-groups) says that you put the SGs on the _targets_. Our SGs do have `0.0.0.0/0` on them, so maybe they're not getting picked up?

**Comment by jgn** [comment]
So . . . I guess it would be nice were there interior lines connecting the nlb to each of the targets. Meanwhile, I wonder if it makes sense to somehow get a line from the Internet to the nlb itself.

![nlb](https://user-images.githubusercontent.com/47090/48027291-09806000-e10e-11e8-8bf0-084695423d96.png)

**Comment by 0xdabbad00** [comment]
Closing due to staleness.  I suspect in this case, the EC2s have security groups open to 0.0.0.0/0 and therefore it is showing a line from the Internet to the EC2's.  When things are open to the Internet, I don't bother showing lines from the other resources, since it is implied.  This is described in https://duo.com/blog/spotting-misconfigurations-with-cloudmapper
