### ISSUE TITLE
Support ALBs and NLBs in addition to ELBs

### ISSUE THREAD

**Issue by pdehlke** [duo-labs/cloudmapper#22]
Collecting the data in collect_data.sh is pretty simple, but I don't stand a snowball's chance of being able to produce a PR for the python bits :)

Thanks!

**Comment by JulesDT** [comment]
I can probably do that. Do we agree that (in terms of AWS CLI)
`aws elb describe-load-balancers` gives you the ELBs
`aws elbv2 describe-load-balancers` gives you the ALBs and NLBs ?

Obviously AWS didn't make this easy so the JSON Blobs structure is different, but no big deal.
Could someone eventually give some demo data so that I can test my code ?

**Comment by JulesDT** [comment]
Opened a PR (https://github.com/duo-labs/cloudmapper/pull/61) to solve this issue, but I couldn't test it.

**Comment by 0xdabbad00** [comment]
Thank you @JulesDT! I'd like someone else to test this with real data, and if possible update the `demo` data with some munged data so the unit tests run over this.  I can spin up an ALB and NLB quickly if no one else already has one in their environment.

**Comment by 0xdabbad00** [comment]
ALB and NLB support should work now thanks to @JulesDT and @heikkiv.
