### ISSUE TITLE
Be able to query the network graph

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#234]
If a box is compromised, you'll want to know what that box could talk to.  
 See https://github.com/disruptops/assess_network as an example.

**Comment by rams3sh** [comment]
Could a graph database be used to import already prepared network data json file ? 

Being able to import this network data into a graph db as neo4j and being able to query within it will be really helpful. One could have a preset of queries for each case of an identified compromise (that possibly cloudmapper can run in the background on the graph db server and get the required info and report it ) which could be used to query the graph db to get the relationship. This will also save from writing multiple code logic in future for each case of an network component exposure / possible privilege escalation path / any attack anomaly which one might hit upon. Everything will boil down to a single query to be sent to the graph db and get the required information back. Any feature extension pertaining to an audit or an observation related to a network diagram or probably any other privilege escalation path (if cloudmapper is able to provide a map of IAM relationships in future like https://github.com/nccgroup/PMapper)  will be just identifying the right query for the graph db and reporting it back to the user.

This kind of usage of relationship graph db is being already used in tool like Bloodhound : https://github.com/BloodHoundAD/BloodHound

The user also can query the diagram the way he/she wants from the graph db directly if needed. This might probably be used / extended across any context where one would need to find a relationship to confirm on a finding.  Just a suggestion. Wanted to put it down here , so that the idea can be reviewed. In my opinion, this should possibly solve many future relationship based feature extensions.

**Comment by 0xdabbad00** [comment]
The project https://github.com/lyft/cartography is focused a lot more on being able to query a graph than I am right now.  So far in my experience, I've mostly only needed to identify single edges, such as the publicly exposed resources accessible from `0.0.0.0/0`.  If I ever do add the functionality to query the graph in order to find paths through it, I'll likely do so by making the data more easily importable into some other tool.  It should be a fairly simple task for someone if they were interested.

**Comment by 0xdabbad00** [comment]
I'm of the belief now that is someone is interested in querying the data from CloudMapper, they should just work off of the data.json file and translate that into whatever shape is needed for their querying tool.
