### ISSUE TITLE
Missing apigateway:GET action in the IAM policy

### ISSUE THREAD

**Issue by wolruf** [duo-labs/cloudmapper#284]
Not sure why #145 didn't update readme.md, I cloned the repo today and a few actions were missing:
apigateway:GET
kms:ListKeyPolicies
lightsail:GetLoadBalancers

**Comment by 0xdabbad00** [comment]
Related discussion in #370 .

**Comment by 0xdabbad00** [comment]
I've sent a PR to add `lightsail:GetLoadBalancers`.

I'm not sure what to do on `apigateway:GET`.  The `SecurityAudit` policy has the following add the end of it:
```
{
                    "Action": [
                        "apigateway:HEAD", 
                        "apigateway:GET", 
                        "apigateway:OPTIONS"
                    ], 
                    "Resource": [
                        "arn:aws:apigateway:*::/restapis", 
                        "arn:aws:apigateway:*::/restapis/*/authorizers", 
                        "arn:aws:apigateway:*::/restapis/*/authorizers/*", 
                        "arn:aws:apigateway:*::/restapis/*/resources", 
                        "arn:aws:apigateway:*::/restapis/*/resources/*", 
                        "arn:aws:apigateway:*::/restapis/*/resources/*/methods/*", 
                        "arn:aws:apigateway:*::/vpclinks"
                    ], 
                    "Effect": "Allow"
                }
```
Since they aren't allowing `GET` on `arn:aws:apigateway:*::/restapis/*`, it worries me that adding that would grant too much privilege, but I don't know enough about API Gateway to make that call right now.
