### ISSUE TITLE
Incomplete stats output

### ISSUE THREAD

**Issue by bnugent** [duo-labs/cloudmapper#299]
On the [referenced SummitRoute blog post](https://summitroute.com/blog/2018/06/06/cloudmapper_stats/), the output of `stats` has a few more categories than what I'm seeing output. Is there an updated `stats_config.yml` file you're using?

**Comment by bnugent** [comment]
The blog post has the following:
```
S3 buckets              0       0
IAM users               0       0
IAM roles               0       0
Route53 hosted zones    0       0
Route53 records         0       0
Route53 domains         0       0
EC2 instances           3       3
EC2 AMIs                0       0
Network ACLs            0       0
Route tables            0       0
EC2 snapshots           0       0
VPC endpoints           0       0
VPN connections         0       0
DirectConnects          0       0
ELBs                    1       1
ELBv2s                  0       1
RDS instances           1       1
Redshift clusters       0       0
ElasticSearch domains   0       0
Elasticache clusters    0       0
SNS topics              0       0
SQS queues              0       0
CloudFronts             0       0
CloudSearch domains     0       0
ECR repositories        0       0
CloudFormation stacks   0       0
Autoscaling groups      0       0
ElasticBeanstalks       0       0
EFS                     0       0
Firehose streams        0       0
Glacier vaults          0       0
KMS keys                0       0
Lambda functions        0       0
Cloudwatch alarms       0       0
Config rules            0       0
Event rules             0       0
Log groups              0       0
```
The output I'm seeing:
```
S3 buckets              0
EC2 instances           0
ELBs                    0
ELBv2s                  0
RDS instances           0
Redshift clusters       0
ElasticSearch domains   0
Elasticache clusters    0
SNS topics              0
SQS queues              0
CloudFronts             0
Autoscaling groups      0
ElasticBeanstalks       0
Firehose streams        0
Glacier vaults          0
KMS keys                0
Lambda functions        0
```
Which seems to match what's in `stats_config.yml`:
```
$ grep 'name: ' stats_config.yaml
- name: S3 buckets
- name: EC2 instances
- name: ELBs
- name: ELBv2s
- name: RDS instances
- name: Redshift clusters
- name: ElasticSearch domains
- name: Elasticache clusters
- name: SNS topics
- name: SQS queues
- name: CloudFronts
- name: Autoscaling groups
- name: ElasticBeanstalks
- name: Firehose streams
- name: Glacier vaults
- name: KMS keys
- name: Lambda functions
```

**Comment by 0xdabbad00** [comment]
I reduced the number of resources that `stats` was showing, partially in order to focus on resources that actually cost money (ex. I removed "Network ACLs"), and partially to simplify it to the resources that seemed most important in the work I had been doing.

You would need to take the removals from https://github.com/duo-labs/cloudmapper/commit/e7885851cae42174ad7e4bed251742c9645dbc94#diff-6011e976315d512271c0a82182a721d9
and add them to https://github.com/duo-labs/cloudmapper/blob/master/stats_config.yaml 

Some of this removal was also to reduce the data to make it easier for a new `dashboard` command I've developed privately but haven't had a chance yet to clean up and release yet (will come soon... might be 2-3 weeks).  This is demo'd at http://www.youtube.com/watch?v=9DOMdW6_sYE&t=39m7s

**Comment by bnugent** [comment]
Thanks Scott! First, `dashboard` looks dope. Looking forward to it.

As for `stats`, I think the missing resource type that caused me to submit this issue was ECR repos, (which do cost money for storage and data transfer if that's what you're indexing on). I'll check out the diff you referenced.

**Comment by 0xdabbad00** [comment]
I'm going to have some sort of switch to enable or disable collecting all of the stats collected previously.  This will be a command-line parameter such as a `--stats-all`.  I think it's best to keep the default as is, because some of the items don't really make sense to compare against in a chart as is displayed in the report command.  The purpose of the chart drawn in the report is to give you an understanding of the relative "sizes" of the accounts, where an account with lot's of EC2's is "larger" than one with fewer.  Even that simple comparison can be misleading if you have an account with a thousand t2.micros that are all exactly the same versus an account with all sorts of workloads running on different larger instances.  However, it doesn't really make sense to compare a count of EC2s against the number of Direct Connects in an account.

I also need to expand the color palette for this.  As you can see, my limited 12 colors becomes incoherent when 34 items are displayed.
<img width="957" alt="Screen Shot 2019-04-29 at 9 08 56 AM" src="https://user-images.githubusercontent.com/1979334/56906444-793d2b00-6a5f-11e9-86f1-bbf5a452408e.png">

**Comment by 0xdabbad00** [comment]
There is now a flag `stats_all_resources` for the `stats` and `report` commands.  Here's an example report of the differences.

Default:
<img width="961" alt="Screen Shot 2019-04-29 at 9 59 53 AM" src="https://user-images.githubusercontent.com/1979334/56909785-2adf5a80-6a66-11e9-8674-b70c911ea81c.png">

With `stats_all_resources`:
<img width="969" alt="Screen Shot 2019-04-29 at 10 00 00 AM" src="https://user-images.githubusercontent.com/1979334/56909800-32066880-6a66-11e9-91bc-5675824b7383.png">
