### ISSUE TITLE
collect specific region

### ISSUE THREAD

**Issue by rsiripan** [duo-labs/cloudmapper#304]
in the config file, is anyway we can run only specific region instead of list all region?

also we have received this error, any suggestion? missing describe from the policy?
An error occurred (AccessDeniedException) when calling the GetStages operation: User: arn:aws:iam::111111111:user/111111 is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-1::/restapis/d7316bv5ug/stages

**Comment by 0xdabbad00** [comment]
There is not currently a way to collect data only for a specific region.  It would speed up the collection, but I think a common use case is just to start the collection and come back to later, since even for a single region it would take at least a minute to collect everything in it.

As for the error, there are some additional privileges I need to add to the instructions, or just stop collecting that info.  The data collected there is only used by the `api_endpoints` command, so it can likely be ignored for most use cases.

**Comment by rsiripan** [comment]
thanks for quick response -- 

we tried to prepare got zero built, any suggestion?

run:- 

python cloudmapper.py prepare --account <name inside the config file>

then we got this:- 

Building data for account <account_name> (123456789)
- 0 external CIDRs built
- 0 connections built

**Comment by 0xdabbad00** [comment]
Check the "./account-data/" directory has files in it for that account name to ensure the `collect` command worked correctly and that the account names match between what was used for `collect` and what was used for `prepare`.

**Comment by rsiripan** [comment]
@0xdabbad00 thank you!

**Comment by 0xdabbad00** [comment]
I'm closing this as I assume this solved your problem, and as for the concept of specifying a region for collection, I think it will just cause things to break right now if it were attempted, so I'm of the opinion that it's out of scope for work that would have enough benefit to be worth the effort.
