### ISSUE TITLE
Feature Request - Identify Unused Security Groups

### ISSUE THREAD

**Issue by rams3sh** [duo-labs/cloudmapper#372]
From an audit standpoint and infrastructure optimization standpoint, it would be great if cloudmapper can identify all unused security groups and call it out as part of the audit feature. 

Also I understand from the recently created Issue No #365 where you have said that you would have to identify all the services that utilizes security groups. This feature can be built on top of that logic , where you can get all the resources that can have security groups attached to them and get their corresponding security groups and co-relate with existing set of all security groups. The difference will be the remaining unused security groups.

**Comment by 0xdabbad00** [comment]
This will be tough because in #365 I identified 30+ services, in addition to the PrivateLink ones, that support Security Groups, and I don't plan on supporting all services in CloudMapper's network diagrams.  However, I could make a best effort advice based on the services I do support.  So there could be cases where someone is using a Security Group for something like SageMaker, that I might not support, and I would end up stating the Security Group is unused.

**Comment by rams3sh** [comment]
Sure. That seems logical. Cool then , please go ahead with whichever status deems fit for this issue request .

**Comment by 0xdabbad00** [comment]
Most tools that do this do a diff between `ec2 describe-network-interfaces` and `ec2 describe-security-groups` . For example Prowler, https://github.com/toniblyx/prowler/blob/d36674a2978cddbe4ea69c9d85dd13fa2c8de426/checks/check_extra75

I'm trying to figure out if there is anything that doesn't use network interfaces that would require using a different approach.

**Comment by 0xdabbad00** [comment]
Resolved by #482
