### ISSUE TITLE
Exception: Could not find parent for Redshift node

### ISSUE THREAD

**Issue by bradleyess** [duo-labs/cloudmapper#405]
I'm unable to prepare Cloud Mapper as I am receiving the following error. I'm curious if there is something simple I'm missing here.

`Exception: Could not find parent for Redshift node, was looking for VPC vpc-1e27647b`

**Comment by bradleyess** [comment]
PS. Thank you so much for the tool - I can't wait to use it.

**Comment by 0xdabbad00** [comment]
Sorry for the delay. Do you have `vpc-1e27647b` in your environment and is your Reshift node part of it?  Did you apply any filters that would have excluded that VPC?  That exception is pretty much a sanity check that I didn't think would ever happen.  One possibility is when you ran `collect` that there was a race condition between when the VPC's were listed and when the Redshift nodes were listed, and the Redshift node and VPC being created or deleted between then, although that would not be very likely.

**Comment by StephenKing** [comment]
Hi, I just ran into the same issue. I just executed CloudMapper for the very first time against this account.

Everything works, when I'm not limiting the `prepare` step. If I'm limiting it to an arbitrary VPC it fails. 

The error message indicates however that it was looking for a VPC from _another_ account. It turned out, that my current `AWS_PROFILE` was actually pointing to that account and - although I've specified the `--account prod` argument to CloudMapper, it was actually scanning the dev account.

Not sure if CloudMapper could maybe detect that the account ID received from STS get-caller-identity doesn't match the account ID specified in the `config.json`.

**Comment by 0xdabbad00** [comment]
@StephenKing Thank you for the clarification of what was possibly impacting @bradleyess.  I'm going to assume that was the issue and close this due to staleness as there has not been a response from @bradleyess and it sounds like this could have been the same issue.

As for checking the account ID is correct in the `config.json`, this is related to #286 which would resolve this, as the concept there is to not have a config.json in the first place, or to somehow auto-generate it.
