### ISSUE TITLE
unable to generate report

### ISSUE THREAD

**Issue by sachintandon** [duo-labs/cloudmapper#420]
Hi ,

I am currently unable to generate the report and use stats command . the cloudmapper fails with the below error . Can you kindly let me know what exactly is wrong in my configuration.

```
$ python cloudmapper.py report --config config.json --accounts <account_name>
* Getting resource counts
Traceback (most recent call last):
  File "cloudmapper.py", line 73, in <module>
    main()
  File "cloudmapper.py", line 67, in main
    commands[command].run(arguments)
  File "/root/cloudmapper/commands/report.py", line 374, in run
    report(accounts, config, args)
  File "/root/cloudmapper/commands/report.py", line 62, in report
    account_stats[account['name']] = get_account_stats(account,args.stats_all_resources)
  File "/root/cloudmapper/shared/common.py", line 219, in get_account_stats
    bucket_region = get_parameter_file(region, 's3', 'get-bucket-location', bucket)['LocationConstraint']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by 0xdabbad00** [comment]
It looks like you updated CloudMapper without rerunning `collect` maybe?  My guess is the `get-bucket-location` call was never made previously.  Every release of CloudMapper assumes that the latest `collect` has been run as well.

**Comment by 0xdabbad00** [comment]
Closing due to staleness

**Comment by royharoush** [comment]
Reopening this issue.
Does it make sense that I'm getting this error if I'm getting accesses denied on a small subset of resources. 

![image](https://user-images.githubusercontent.com/8113056/64490769-24a98800-d269-11e9-976d-00e3c65745c5.png)

**Comment by 0xdabbad00** [comment]
@royharoush It looks like you are being denied any access to a specific bucket.  I'm not sure how to deal with situations like this in a generic way as they are happening more frequently for people (see #537). 

My default response is that CloudMapper requires certain privileges and if you don't have them, then you should expect CloudMapper to break.  It's possible to develop workarounds on a case by case basis, so I may eventually start adding some of these exceptions somehow, but it needs to be done in such a way that I don't hide problems.  For example, if your S3 bucket is publicly accessible, CloudMapper will not be able to tell you that, because it has no access to read the policy, so I need to ensure you are still informed that info about this S3 bucket could not be accessed.

**Comment by royharoush** [comment]
I have the required permissions, but I think this bucket, due to sensitivity, as a deny for everyone except very specific entities. This account has about 400 buckets, it's unfortunate a log will be created due to a security measure applied on just one of them :) 
Either way, I've opened a new issue(#544  ), as this might different from the issue described here in this main thread and didn't want to hijack it.
