### ISSUE TITLE
S3 and SQS missing from network diagram

### ISSUE THREAD

**Issue by gaganbioinfo** [duo-labs/cloudmapper#528]
Hi Scott

When I collect data of my AWS account I see json file created for S3 and SQS but after executing prepare command I do not see S3 and SQS in my AWS architecture diagram being generated by cloudmapper. Also my S3 buckets are not public so as to create secure architecture. Can you please help with commands that I can use in order to make components visible?

Appreciate your help and building such a great tool.

**Comment by 0xdabbad00** [comment]
S3 and SQS are only displayed if you have a VPC Endpoint for those services.

**Comment by 0xdabbad00** [comment]
Only resources with Security Groups are currently within scope for the network visualizations.  I think the best solution to maintain the existing scope of the project, and reduce confusion, is to label these end-points as being VPC endpoints, so instead of an icon of an S3 bucket, it would some generic VPC end-point icon.  I know many would prefer that I expand the scope to somehow show the actual S3 buckets, but I don't personally have the time or interest to add that.
