### ISSUE TITLE
Image Download Zero bytes

### ISSUE THREAD

**Issue by winnettjohnston** [duo-labs/cloudmapper#542]
After successfully displaying the image, i select the button to download the image to a file. The file begins to download then stops. No error in the webserver or the browser.

Is there any other way to get the image?

**Comment by 0xdabbad00** [comment]
I have not experienced that. Did you look in the browser console for javascript errors?  Was this a large file? Maybe something on your system prevents your browser from downloading files? Unfortunately I don't have any idea what might have happened.  The code for creating the image is in cytoscape.js so I think the problem is going to be outside of the scope of CloudMapper to resolve.
