### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable  

### ISSUE THREAD

**Issue by royharoush** [duo-labs/cloudmapper#544]
When trying to run report after executing collect. 
Does it make sense that I'm getting this error if I'm getting accesses denied on a small subset of resources.

image
![image](https://user-images.githubusercontent.com/8113056/64490819-a3062a00-d269-11e9-84ab-3e40a8ea4339.png)

**Comment by 0xdabbad00** [comment]
I'm closing this as I believe the situation was explained in #420.  You appear not to have privileges, either due to your principal's own IAM, an SCP applied to them, or the policy on the bucket itself.  The paths forward I see with CloudMapper for this issue for you would be:
1. Get the privileges needed
2. Add code to bypass this issue or remove references to this S3 bucket from your `s3-list-buckets.json` file

**Comment by ulte** [comment]
@0xdabbad00 same issue here. We unfortunately have about 30 s3 buckets with source IP restriction. As I can't run this report from that IP, we get access denied, thus reporting fails with "TypeError: 'NoneType' object is not subscriptable". 
Is your recommendation to comment or delete each of these buckets from all of the s3-list-buckets.json?

Seems like a common use case btw.

**Comment by 0xdabbad00** [comment]
@ulte I don't have a good answer.  My default answer has thus far been that any problems encountered running CloudMapper without the necessary privileges is outside of the scope of the project.

One option, as you mentioned is to manually modify your data to workaround these limitations.  No one wants to do that unless they are really in a pinch.

Another option is to give CloudMapper the access it expects, which is not really possible or desirable for your situation, but can be in some others.

Another option is to add code to ignore these failures.  The concerns there are:
1. It creates a cat and mouse game of continually having to add workaround code for different environments that are blocking different calls.
2. The potential for bugs in CloudMapper increases dramatically in these situations as there are lots of assumptions in the code that it has access.
3. It potentially hides problems. For example, if someone has an SCP that denies them the ability to look at an S3 bucket in an account, but that S3 bucket is publicly readable, then CloudMapper will not be able to identify that the bucket is otherwise public.

I think we do need to add workaround code to ignore these problems, and somehow bubble up to the user that they didn't have expected access.  I just haven't faced the situation yet to take the time to resolve it.

**Comment by Viss** [comment]
I'm encountering this issue.
Is it possible to just have cloudmapper just ignore the buckets if the account doesnt have access?

**Comment by murph-cat** [comment]
Just keep a file of ignored buckets you have no permission for and throw a warning, don't totally fail to run.

**Comment by Viss** [comment]
yes, that ^
it seems a bit overkill to completely prevent the entire tool from running on the rest of an environment because there is literally one s3 bucket that the account doesn't have access to.

**Comment by royharoush** [comment]
what he said
