### ISSUE TITLE
Why use pipenv in docker?

### ISSUE THREAD

**Issue by kminehart** [duo-labs/cloudmapper#642]
Seems like an unnecessary layer of abstraction. Docker is already an isolated environment, using pipenv complicates things and makes this container difficult to use.

You should be able to:

```
docker run -p 8000:8000 cloudmapper webserver --public
```

but instead you have to exec into the container, activate the pipenv shell, and then run the script. What value does pipenv provide in a docker container?

**Comment by 0xdabbad00** [comment]
Using pipenv was due to that being how the normal install works, and I wanted to keep the same process in Docker so I didn't have to worry about maintaining something else.   As mentioned in #595, I would like to switch back from using pipenv to using virtualenv again at some point which means using a requirements.txt file and that would more easily allow the virtualenv step to be skipped.

**Comment by andrewkrug** [comment]
@0xdabbad00 recently I've had great success using python poetry instead of requirements.txt OR Pipenv.  https://github.com/python-poetry/poetry

**Comment by mwarkentin** [comment]
I think you could also use “pipenv lock —requirements” to render a requirements.txt for use inside of docker while still enabling pipenv for host level development.

**Comment by 0xdabbad00** [comment]
Closing this as I've submitted to a PR to remove pipenv entirely. #696
