### ISSUE TITLE
Add parameters to ignore errors during API requests

### ISSUE THREAD

**Issue by dlehle** [duo-labs/cloudmapper#707]
Hello all,

we use the cloudmapper collect script in our Jenkins pipeline. The problem is, that if there are errors during some of the API requests (e.g. when requesting tags for S3 buckets, but there do not exist any tags) the script ends with exist code != 0 and our pipeline fails. We want to ignore such errors when there are no tags.

Is there a parameter or something else which can be used to force exit code to be 0?

Regards
Daniel

**Comment by 0xdabbad00** [comment]
In the general case, I would not want to swallow errors,  so I would want to add functionality to CloudMapper to always return zero.  I think you could do something like `python cloudmapper.py collect --account test || exit 0` in order to get the functionality you want.

In this specific case, if a S3 bucket does not have tags and I try to get tags for it, and I can identify that the cause of the error is because the bucket did not have tags, then this should not result in an error for CloudMapper.
