### ISSUE TITLE
what are the guidance for visualizing large JSON.files

### ISSUE THREAD

**Issue by naveen2603** [duo-labs/cloudmapper#73]
some of our accounts have 1000's of EC2 instances. the combined JSON is 1000MB+.
The UI is not loading or taking forever to display this information. 
Any guidance on how to handle the large number of nodes/json in the UI ?

Thank you for the support..

**Comment by 0xdabbad00** [comment]
See the options in the `prepare` phase as documented in https://github.com/duo-labs/cloudmapper/blob/master/README.md#3-prepare-the-data

Specifically, reducing the VPC's and regions displayed, using `--collapse-by-tag`, and `--no-internal-edges` will help.  Those are currently the only options.

**Comment by 0xdabbad00** [comment]
I'm closing this. Let me know if you have alternative ideas on how to reduce the number of nodes displayed.   There are also enhancements planned in https://github.com/duo-labs/cloudmapper/issues/36 and https://github.com/duo-labs/cloudmapper/issues/71 to reduce the number of nodes further.

With thousands of nodes, there is not going to be a way to make a diagram that provides much value because it will be too complex and over-whelming, so instead of trying to display such a diagram, I'm focused more on trying to reduce the number of nodes attempted to be displayed by either filtering things out that aren't relevant to someone's current interests, or by collapsing multiple nodes into one based on some similarity.

**Comment by GauravThukral** [comment]
python cloudmapper.py prepare --config config.json --account accountname is giving me 
- 0 external CIDRs built
- 0 connections built
Complete
/web/data.json is only having few information

**Comment by 0xdabbad00** [comment]
@GauravThukral Try visualizing the demo data first to ensure everything is functioning. If your account has no network resources in it (no EC2, RDS, or ELB nodes), then it will not show anything.
