### ISSUE TITLE
Export map to static image file

### ISSUE THREAD

**Issue by kirkbrady** [duo-labs/cloudmapper#79]
Hi,

Can this be run from the cli to export the generated maps as a static image file?

Cheers

**Comment by 0xdabbad00** [comment]
No, and unfortunately you'll find that the generated images often look bad before you move some things around manually.  The best path to accomplish this would likely be to use https://github.com/cytoscape/cytosnap

I have considered trying to perform the initial layout as an interim phase between the `prepare` and `serve` because when you initially load CloudMapper in your browser, it takes a while to show the initial layout because javascript code is chugging along trying to perform the layout.  This can take minutes and looks like the server is locked up in larger diagrams, so it would be better to do that "offline" before showing it in the browser.

**Comment by 0xdabbad00** [comment]
I'm closing this as a `wontfix` because of the reasons stated above with regard to the assumed manual work someone will need to do in order to clean up the generated graphs.  Unless the auto-layout of the graphs improves significantly this feature just wouldn't satisfy many people.
