### ISSUE TITLE
"Note the Network Visualization functionality (command prepare) is no longer maintained."

### ISSUE THREAD

**Issue by elliotrpage** [duo-labs/cloudmapper#909]
Thank you for writing this tool, we have found it very useful.

About the notice in the subject line, I wondered if there was a reason/ rationale behind it? 
I'm not here to demand/expect this to change(!) but just wanted to understand.

Is there an alternative you would recommend? We have found the Network Viz functionality quite useful while finding our feet with AWS.

Best,
Elliot

**Comment by 0xdabbad00** [comment]
A few reasons:
- My professional focus has moved beyond maintaining the tool, and so although I'll try to review some PRs, I want to cut back on doing anything for some areas so even the minimal maintenance isn't overwhelming.
- The network viz becomes overly complicated in large environments and doing things to attempt to improve this would require rethinking and rewriting large parts of CloudMapper.  This would include a better ability to group resources, adding more visual features to show when things are grouped or excluded, and creating new network layout algorithms as the open-source options don't provide some of the things I would have liked.
- The purpose of network viz was confusing to many people who didn't understand why things like S3 buckets weren't being shown (because the network viz only deals with things that can have Security Groups).
- AWS's has changed many concepts and added new features for how networking works which is hard to keep up with, and so in many networks today the network visualization can be wrong, if features released within the past few years are being used.
- The networking functionality has no unit tests (neither does most of CloudMapper, but especially the network viz) making the code extremely fragile and PRs to it have at times broken functionality.
